#define PORT 5555
#define MENSAJE_MAXIMO 1024
#define DATO_MAXIMO 100
#define STRING_MAXIMO 200

#define ANCHO_AULA 10
#define ALTO_AULA 10
#define FILA_SALIDA 0
#define COLUMNA_SALIDA -1
#define RESCATISTAS 10
#define MAXIMO_POR_POSICION 10